---
title: "RProject"
author: "Fernando Pérez"
date: "24 de noviembre de 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(jsonlite)
library(ggplot2)
```


## R Markdown

```{r}


link <- "https://min-api.cryptocompare.com/data/histoday?fsym=BTC&tsym=USD&limit=2000&aggregate=3&e=CCCAGG"

data <- fromJSON(link)

 x = as.POSIXct(data$Data$time,origin = "1970-01-01",tz = "GMT")
data2 <- data.frame("time" = x, "price" = data$Data$open)

g <- ggplot(data2) + aes(x = time, y = price) + geom_point()
g
```


## By Hour

```{r}

actualTime <- round(as.numeric(Sys.time()))
numberofpoint <- 2000
cripto <- "BTC"
priceToCompare <- "USD"
 
link2 <- paste("https://min-api.cryptocompare.com/data/histohour?fsym=",cripto, "&tsym=", priceToCompare,"&limit=", numberofpoint, "&aggregate=1&toTs=",actualTime, "&extraParams=your_app_name", sep = "")


data2 <- fromJSON(link2)


x2 = as.POSIXct(data2$Data$time,origin = "1970-01-01",tz = "GMT")
data2 <- data.frame("time" = x2, "price" = data2$Data$open)

g1 <- ggplot(data2) + aes(x = time, y = price) + geom_line()
g1


```
## By minute

```{r}

actualTime <- round(as.numeric(Sys.time()))
numberofpoint <- 2000
cripto <- "ETH"
priceToCompare <- "USD"
 
link3 <- paste("https://min-api.cryptocompare.com/data/histominute?fsym=",cripto, "&tsym=", priceToCompare,"&limit=", numberofpoint, "&aggregate=1&toTs=",actualTime, "&extraParams=your_app_name", sep = "")


data3 <- fromJSON(link2)


x3 = as.POSIXct(data3$Data$time,origin = "1970-01-01",tz = "GMT")
data2 <- data.frame("time" = x3, "price" = data3$Data$open)

g3 <- ggplot(data3) + aes(x = time, y = price) + geom_line()
g3

```

```{r}
actualTime <- round(as.numeric(Sys.time()))
numberofpoint <- 200
cripto <- "ETH"
priceToCompare <- "USD"
platform = "Binance" 

link4 <- paste("https://min-api.cryptocompare.com/data/exchange/histohour?e=", platform, "&tsym=", cripto, "&limit=", numberofpoint, "&aggregate=1&toTs=", actualTime, "&extraParams=your_app_name", sep = "")

data4 <- fromJSON(link4)


x4 = as.POSIXct(data4$Data$time,origin = "1970-01-01",tz = "GMT")
data4 <- data.frame("Time" = x4, "Volume" = data4$Data$volume)

g4 <- ggplot(data4) + aes(x = Time, y = Volume) + geom_line()
g4




```

```{r}
  a <- 0

actualTime <- round(as.numeric(Sys.time()))
numberofpoint <- 2000
cripto <- "ETH"
priceToCompare <- "USD"
data.frame()
df <- data.frame(Date=as.Date(character()),
                 Price=double()) 
for (n in 1:10){
  Time <- actualTime - 3600*numberofpoint*n
  link5 <- paste("https://min-api.cryptocompare.com/data/histohour?fsym=",cripto, "&tsym=", priceToCompare,"&limit=", numberofpoint, "&aggregate=1&toTs=",Time, "&extraParams=your_app_name", sep = "")
  data5 <- fromJSON(link5)
  
  df2 <- data.frame("Date" =as.POSIXct(data5$Data$time,origin = "1970-01-01",tz = "GMT"), "Price" = data5$Data$Price )
  df <- rbind(df, df2)
}

```


