---
title: "News crypto occurence"
output: html_document
---
```{r}
#install.packages("tidyverse")
#install.packages("jsonlite")
#install.packages("stringr")
```
First available news :      2013-08-01 18:30:00
```{r}
rm(list=ls()) 
library(tidyverse)
library(jsonlite)
library(stringr)
library(lubridate)
```
Description
Returns a dataframe with the 50 latests news from the timestamp passed in argument

Usage
Tsp_data(timestamp)

Arguments
timestamp a character of numerical value representing t
```{r cars}
Tsp_data <- function(timestamp) {
  link <- paste("https://min-api.cryptocompare.com/data/v2/news/?lTs=", timestamp, sep="")
  ndata <- fromJSON(link)
  data2 <- data.frame("time" = as.integer(ndata$Data$published_on), "body" = as.character(ndata$Data$body))
  return(data2)
}
```

```{r}
dl_data_from <- function(timestp) {
new_data <- NULL
fdata <- NULL
timenow <- as.numeric(as.POSIXct("2018-12-01 1:00:00 EST"))
while (timestp < timenow)
{
  new_data <- Tsp_data(timenow)
  fdata <- rbind(fdata,new_data)
  timenow <- min(new_data$time)
}
print(paste("Last news found was released on ", as.POSIXct(min(fdata$time), origin="1970-01-01"), sep = "" ))
return(fdata)
}
```

```{r}
CryptoCurrencyName <- function(CryptoSymbol) {
  dico <- read.csv2("crp_dic.csv")
  Symb <- dico %>% filter(Symbol == CryptoSymbol)
  return(as.character(Symb$Name))
}
```

```{r}
analyse_crp_news <- function(databodynews, currencySymbol) {
  currencyName <- CryptoCurrencyName(currencySymbol)
  analysed <- databodynews %>% mutate(!!currencySymbol :=  ifelse(grepl(as.character(currencyName),body,ignore.case = TRUE), 1, 0) ) 
  return(analysed)
}
```


```{r}
analyse_crps_news <- function(databodynews, currencySymbols) {
  resul <- analyse_crp_news(databodynews, currencySymbols[1])[-2]
for (i in 2:length(currencySymbols))
resul <- cbind(resul, analyse_crp_news(databodynews, currencySymbols[i])[3])
return(resul)
}
```

```{r}
SumlastHour <- function(hourTstp, CrpSymbols, BoolDataNews) {
  res <- BoolDataNews %>% filter(time<hourTstp, time>hourTstp-3600)
  resu <- hourTstp
for (i in 2:length(result)) {
    resa <- res %>% filter(res[i] == 1)
    resu <- cbind(resu, length(resa$time))
}
  resu <- data.frame(resu)
  names(resu) <- c("time", CrpSymbols)
  return(resu)
}
```

```{r}
resTspToHour <- function(resTsp, CrpSymbols) {
  max <- floor_date(as.POSIXct(max(resTsp$time), origin="1970-01-01"), unit = "hour") + 3600
  min <- floor_date(as.POSIXct(min(resTsp$time), origin="1970-01-01"), unit = "hour")

  hourvec <- seq(max, min, by=-3600)
  resul <- NULL
  for (hour in hourvec) {
    resul <- rbind(resul, SumlastHour(hour, CrpSymbols, resTsp))
  }
  return(resul %>% mutate(time = as.POSIXct(time, origin="1970-01-01")))
}
```

```{r}
SumlastDay <- function(dayTstp, CrpSymbols, BoolDataNews) {
  res <- BoolDataNews %>% filter(time<dayTstp, time>dayTstp-3600*24)
  resu <- dayTstp
for (i in 2:length(result)) {
    resa <- res %>% filter(res[i] == 1)
    resu <- cbind(resu, length(resa$time))
}
  resu <- data.frame(resu)
  names(resu) <- c("time", CrpSymbols)
  return(resu)
}
```

```{r}
resTspToDay <- function(resTsp, CrpSymbols) {
  max <- floor_date(as.POSIXct(max(resTsp$time), origin="1970-01-01"), unit = "day") + 3600*24
  min <- floor_date(as.POSIXct(min(resTsp$time), origin="1970-01-01"), unit = "day")

  dayvec <- seq(max, min, by=-3600*24)
  resul <- NULL
  for (day in dayvec) {
    resul <- rbind(resul, SumlastDay(day, CrpSymbols, resTsp))
  }
  return(resul %>% mutate(time = as.POSIXct(time, origin="1970-01-01")))
}
```

```{r}
get_imp_Crp <- function(){
ndata <- fromJSON("https://min-api.cryptocompare.com/data/top/volumes?tsym=USDT")
c(ndata$Data$SYMBOL,"USDT")
}

```

```{r}
#data <- dl_data_from(as.numeric(as.POSIXct("2013-11-25 1:00:00 EST")))
#write.csv(data, "CryptonewsData.csv")
data <- read.csv("CryptonewsData.csv")[-1]
interesting_crypto <- get_imp_Crp()[-c(8,13,15,16)]
result <- analyse_crps_news(data, interesting_crypto)

finalHour <- resTspToHour(result, interesting_crypto)
write.csv(finalHour, "CryptoNewsAnalysedHour.csv")

finalDay <- resTspToDay(result, interesting_crypto)
write.csv(finalDay, "CryptoNewsAnalysedDays.csv")
```
```{r}
for (i in interesting_crypto)
  print(CryptoCurrencyName(i))
```

