---
title: "NEWS"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
install.packages("udpipe")
```

Taking the data from the news
```{r cars}
#link <- "https://min-api.cryptocompare.com/data/histoday?fsym=BTC&tsym=USD&limit=2000&aggregate=3&e=CCCAGG"
news_data <- function() {
link <- "https://min-api.cryptocompare.com/data/v2/news/?lang=EN&sortOrder=latest"
data <- fromJSON(link)
x = as.POSIXct(data$Data$published_on,origin = "1970-01-01",tz = "GMT")
data2 <- data.frame("time" = x, "source" = data$Data$source, "title" = data$Data$title, "body" = data$Data$body,"categories" = data$Data$categories, "tags" = data$Data$tags)
return(data2)
}

```

News analysis
```{r}
library(udpipe)
library(lattice)
library(jsonlite)
library(ggplot2)
#model <- udpipe_download_model(language = "english")
news <- news_data()
```
Text mining
```{r}
Needed <- c("tm", "SnowballCC", "RColorBrewer", "ggplot2", "wordcloud", "biclust", 
    "cluster", "igraph", "fpc")
install.packages(Needed, dependencies = TRUE)

install.packages("Rcampdf", repos = "http://datacube.wu.ac.at/", type = "source")
```
```{r}

library(tm)
docs <- tm_map(toString(news$body[1]),removePunctuation) 

```


NOUN VERB ADJ analysis (maybe not very useful)
```{r}
udmodel_english <- udpipe_load_model(file = 'english-ud-2.0-170801.udpipe')
s <- udpipe_annotate(udmodel_english, news$body[1])
x <- data.frame(s)
## NOUNS
stats <- subset(x, upos %in% c("NOUN")) 
stats <- txt_freq(stats$token)
stats$key <- factor(stats$key, levels = rev(stats$key))
barchart(key ~ freq, data = head(stats, 20), col = "cadetblue", 
         main = "Most occurring nouns", xlab = "Freq")

## ADJECTIVES
stats <- subset(x, upos %in% c("ADJ")) 
stats <- txt_freq(stats$token)
stats$key <- factor(stats$key, levels = rev(stats$key))
barchart(key ~ freq, data = head(stats, 20), col = "purple", 
         main = "Most occurring adjectives", xlab = "Freq")

## VERBS
stats <- subset(x, upos %in% c("VERB")) 
stats <- txt_freq(stats$token)
stats$key <- factor(stats$key, levels = rev(stats$key))
barchart(key ~ freq, data = head(stats, 20), col = "gold", 
         main = "Most occurring Verbs", xlab = "Freq")

## Using RAKE
stats <- keywords_rake(x = x, term = "lemma", group = "doc_id", 
                       relevant = x$upos %in% c("NOUN", "ADJ"))
stats$key <- factor(stats$keyword, levels = rev(stats$keyword))
barchart(key ~ rake, data = head(subset(stats, freq > 3), 20), col = "red", 
         main = "Keywords identified by RAKE", 
         xlab = "Rake")

## Using a sequence of POS tags (noun phrases / verb phrases)
x$phrase_tag <- as_phrasemachine(x$upos, type = "upos")
stats <- keywords_phrases(x = x$phrase_tag, term = tolower(x$token), 
                          pattern = "(A|N)*N(P+D*(A|N)*N)*", 
                          is_regex = TRUE, detailed = FALSE)
stats <- subset(stats, ngram > 1 & freq > 3)
stats$key <- factor(stats$keyword, levels = rev(stats$keyword))
barchart(key ~ freq, data = head(stats, 20), col = "magenta", 
         main = "Keywords - simple noun phrases", xlab = "Frequency")
```





Info for our trading 
```{r}
Currencies = c("USDT" , "BTC", "ETH", "XRP", "LTC")
max_invest_USD = 100000
```


code
## Checking the actual sitution and defining which action have to be done

checkaction takes a vector of currencies to be invested on, the amount of each currency in the portfolio, 
```{r}
checkactions <- function(currencies, amount) {
  actions <- rep(0, length(currencies))
  
  return(actions)
}
```

